inherit_from:
  - .rubocop_airbnb.yml
Rails:
  Enabled: true

LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
  NewCops: enable

