version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4
  node: circleci/node@4.7.0

josbs:
  build:
    docker:
      - image: cimg/ruby:2.7.4-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - ruby/isntall-deps
      - node/install-packages:
          pkg-manager: yarn
  test:
    docker:
      - image: cimg/ruby:2.7.4-node-browsers
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/repo
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/isntall-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
        name: Database setup
        command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check

wordkflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            -build
